spring:
  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_EMPTY


#微信开放平台
componentAppId: wx9a6700dcfc8867aa
componentAppSecret: b6fb9b952f581df671b7dcc42231dc83
#componentAppId: wx81aa03f442e8d692
#componentAppSecret: dd8063fc89b412d9f88d1f3cb2c8a1d3
componentToken: fsrtyuiopfghjksadfe3232a
encodingAesKey: sdfaererit3423828343jeriooweqwqqwq22wwwfdgs

#wechat:
#  appId: wx2ffe2417c6b42f78
#  secret: 2c3b915dd8360206d7a0688c0b59a234
wechat:
  appId: wx2681cc8716638f35
  secret: 1c986340bbf0056ae319555b63f494b4
  mchId: 1569458631
  paterKey: 7bkxZxx2ULEvLG0hjEwAjVi5OD0E4AU1
  cert: C://Users//Admin//Downloads//WXCertUtil//cert//1569458631_20191218_cert//apiclient_cert.p12
  attach: stg
  payNotify: https://open.easy.echosite.cn/wx/pay/payNotify
  refundNotify: https://open.easy.echosite.cn/wx/pay/refundNotify

#wechat:
#  appId: wx097eb9f69920db49
#  secret: 123fdsaJHYUTREWQOKLJGCCBNM654389
#  cert: /User/Document/cert.p12k
#  mchId: 1503679961
#  attach: stg
#  domain: https://open.easy.echosite.cn

#微信支付
defaultAppId: wx097eb9f69920db49
paterKey: 123fdsaJHYUTREWQOKLJGCCBNM654389
mchId: 1503679961
attach: stg
domain: https://open.easy.echosite.cn


sequence:
  snowflake:
    datacenterId: 16
    workerId: 21