spring:
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_EMPTY


#微信开放平台
componentAppId: wx81aa03f442e8d692
componentAppSecret: dd8063fc89b412d9f88d1f3cb2c8a1d3
componentToken: fsrtyuiopfghjksadfe3232a
encodingAesKey: sdfaererit3423828343jeriooweqwqqwq22wwwfdgs